// Autogenerated from Pigeon (v9.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BrightnessMessage;

@interface BrightnessMessage : NSObject
+ (instancetype)makeWithBrightnessValue:(nullable NSNumber *)brightnessValue;
@property(nonatomic, strong, nullable) NSNumber * brightnessValue;
@end

/// The codec used by FlutterBrightnessApi.
NSObject<FlutterMessageCodec> *FlutterBrightnessApiGetCodec(void);

@interface FlutterBrightnessApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)getDefaultDeviceBrightnessWithCompletion:(void (^)(BrightnessMessage *_Nullable, FlutterError *_Nullable))completion;
- (void)getPreferredDeviceBrightnessWithCompletion:(void (^)(BrightnessMessage *_Nullable, FlutterError *_Nullable))completion;
- (void)onDeviceBrightnessChangedBrightness:(BrightnessMessage *)brightness completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
