// Autogenerated from Pigeon (v9.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class BrightnessMessage {
  BrightnessMessage({
    this.brightnessValue,
  });

  int? brightnessValue;

  Object encode() {
    return <Object?>[
      brightnessValue,
    ];
  }

  static BrightnessMessage decode(Object result) {
    result as List<Object?>;
    return BrightnessMessage(
      brightnessValue: result[0] as int?,
    );
  }
}

class _FlutterBrightnessApiCodec extends StandardMessageCodec {
  const _FlutterBrightnessApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BrightnessMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return BrightnessMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterBrightnessApi {
  static const MessageCodec<Object?> codec = _FlutterBrightnessApiCodec();

  BrightnessMessage getDefaultDeviceBrightness();

  Future<BrightnessMessage> getPreferredDeviceBrightness();

  void onDeviceBrightnessChanged(BrightnessMessage brightness);

  static void setup(FlutterBrightnessApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterBrightnessApi.getDefaultDeviceBrightness', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final BrightnessMessage output = api.getDefaultDeviceBrightness();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterBrightnessApi.getPreferredDeviceBrightness', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final BrightnessMessage output = await api.getPreferredDeviceBrightness();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterBrightnessApi.onDeviceBrightnessChanged', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.FlutterBrightnessApi.onDeviceBrightnessChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BrightnessMessage? arg_brightness = (args[0] as BrightnessMessage?);
          assert(arg_brightness != null,
              'Argument for dev.flutter.pigeon.FlutterBrightnessApi.onDeviceBrightnessChanged was null, expected non-null BrightnessMessage.');
          api.onDeviceBrightnessChanged(arg_brightness!);
          return;
        });
      }
    }
  }
}
